---
- name: install various games and emulators (void)
  when: ansible_distribution == "void"
  become: yes
  xbps:
    name: "{{item}}"
    state: present
  with_items:
    - nethack
    - higan

- name: install steam
  include: install_steam.yml
  when: install_steam

- name: dwarf fortress
  include: dwarf_fortress.yml
  when: install_dwarf_fortress
