---
- name: install python and related tooling (Void)
  become: yes
  when: ansible_os_family == "void"
  xbps:
    name: "{{item}}"
    state: latest
  with_items:
    - python-pip
    - python-virtualenv
