---

- name: install misc dev tools
  become: yes
  when: ansible_os_family == "void"
  xbps:
    name: "{{item}}"
    state: latest
  with_items:
    - make
    - bmake
    - discount
    - git-all
    - graphviz
    - mscgen
    - perf
    - strace
    - the_silver_searcher
