---
- name: create directories
  become: no
  file:
    path: "{{item}}"
    state: "directory"
    owner: '{{ansible_user_id}}'
  with_items:
    - "{{ansible_env.HOME}}/tmp/"
    - "{{ansible_env.HOME}}/tmp/git/"
    - "{{ansible_env.HOME}}/tmp/src/"
    - "{{ansible_env.HOME}}/bin/"
    - "{{ansible_env.HOME}}/dev/"
